# Generated by Django 3.2.9 on 2022-01-24 00:09

import apps.ads_api.constants
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                ("portfolio_id", models.PositiveBigIntegerField(null=True)),
                (
                    "sponsoring_type",
                    models.CharField(
                        choices=[
                            ("sponsoredProducts", "SP"),
                            ("sponsoredBrands", "SB"),
                        ],
                        default="sponsoredProducts",
                        max_length=99,
                    ),
                ),
                (
                    "targeting_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto")],
                        default="manual",
                        max_length=99,
                    ),
                ),
                (
                    "serving_status",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN_ARCHIVED", "Archived"),
                            ("CAMPAIGN_PAUSED", "Paused"),
                            ("CAMPAIGN_STATUS_ENABLED", "Enabled"),
                            ("ADVERTISER_PAYMENT_FAILED", "Payment Failed"),
                            ("ADVERTISER_PAYMENT_FAILURE", "Payment Failure"),
                            ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                            ("PENDING_START_DATE", "Pending Start Date"),
                            ("CAMPAIGN_INCOMPLETE", "Incomplete"),
                            ("ENDED", "Ended"),
                        ],
                        default="CAMPAIGN_STATUS_ENABLED",
                        max_length=99,
                        null=True,
                    ),
                ),
                (
                    "last_updated_date_on_amazon",
                    models.PositiveBigIntegerField(default=0, null=True),
                ),
                ("campaign_name", models.CharField(default="", max_length=99)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=99,
                    ),
                ),
                (
                    "placement_tos_mult",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(900),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "placement_pp_mult",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(900),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "bidding_strategy",
                    models.CharField(
                        choices=[
                            ("legacyForSales", "Down Only"),
                            ("autoForSales", "Up & Down"),
                            ("manual", "Fixed Bids"),
                        ],
                        default="legacyForSales",
                        max_length=99,
                    ),
                ),
                ("daily_budget", models.PositiveIntegerField(default=20)),
                ("premium_bid_adjustment", models.BooleanField(default=False)),
                ("managed", models.BooleanField(default=False)),
                (
                    "target_acos",
                    models.PositiveSmallIntegerField(
                        default=35,
                        validators=[
                            django.core.validators.MaxValueValidator(199),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "asins",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=99),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "campaign_purpose",
                    models.CharField(
                        choices=[
                            ("Discovery", "Discovery"),
                            ("Research", "Research"),
                            ("Scale", "Scale"),
                            ("GP", "GP"),
                        ],
                        default="",
                        max_length=99,
                        null=True,
                    ),
                ),
                (
                    "manual_type",
                    models.CharField(
                        choices=[("Product", "Product"), ("Keyword", "Keyword")],
                        default="",
                        max_length=99,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DefaultKeywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asin", models.CharField(default="", max_length=99)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Negative", "Negative"),
                            ("NeverNegative", "Never Negative"),
                        ],
                        default="Negative",
                        max_length=99,
                    ),
                ),
                ("keyword_text", models.CharField(default="", max_length=99)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=[
                            ("US", "Us"),
                            ("CA", "Ca"),
                            ("MX", "Mx"),
                            ("UK", "Uk"),
                            ("AU", "Au"),
                            ("DE", "De"),
                            ("ES", "Es"),
                            ("FR", "Fr"),
                        ],
                        default="US",
                        max_length=99,
                    ),
                ),
                (
                    "marketplace_string_id",
                    models.CharField(
                        choices=[
                            ("ATVPDKIKX0DER", "US"),
                            ("A2EUQ1WTGCTBG2", "CA"),
                            ("A1AM78C64UM0Y8", "MX"),
                            ("A1F83G8C2ARO7P", "UK"),
                            ("A39IBJ37TRP1C6", "AU"),
                            ("A1PA6795UKMFR9", "DE"),
                            ("A1RKKUPIHCS9HS", "ES"),
                            ("A13V1IB3VIYZZH", "FR"),
                        ],
                        default="ATVPDKIKX0DER",
                        max_length=99,
                    ),
                ),
                ("entity_id", models.CharField(max_length=99)),
                ("valid_payment_method", models.BooleanField(default=False)),
                ("nickname", models.CharField(default="", max_length=99)),
                ("monthly_budget", models.PositiveIntegerField(blank=True, null=True)),
                ("managed", models.BooleanField(default=False)),
                ("research_mode", models.BooleanField(default=True)),
                (
                    "profile_server",
                    models.CharField(
                        default=apps.ads_api.constants.ServerLocation["NORTH_AMERICA"],
                        max_length=99,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                ("profile_id", models.PositiveBigIntegerField(null=True)),
                ("report_type", models.CharField(default="", max_length=99)),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Amazon Failure"),
                            ("INTERNAL_PROCESSED", "Internal Processed"),
                            ("INTERNAL_FAILURE", "Internal Failure"),
                        ],
                        default="IN_PROGRESS",
                        max_length=99,
                    ),
                ),
                ("report_location", models.CharField(default="", max_length=255)),
                ("report_for_date", models.DateField(null=True)),
                ("report_server", models.CharField(default="", max_length=99)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                (
                    "keyword_type",
                    models.CharField(
                        choices=[("Positive", "Positive"), ("Negative", "Negative")],
                        default="Positive",
                        max_length=99,
                    ),
                ),
                ("ad_group_id", models.PositiveBigIntegerField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=99,
                    ),
                ),
                ("expression_text", models.CharField(default="", max_length=99)),
                ("expression_type", models.CharField(default="", max_length=99)),
                (
                    "resolved_expression_text",
                    models.CharField(default="", max_length=99),
                ),
                (
                    "resolved_expression_type",
                    models.CharField(default="", max_length=99),
                ),
                (
                    "targeting_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Auto")],
                        default="manual",
                        max_length=99,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        decimal_places=2, default=0.11, max_digits=8, null=True
                    ),
                ),
                (
                    "serving_status",
                    models.CharField(
                        choices=[
                            ("TARGETING_CLAUSE_ARCHIVED", "Target Archived"),
                            ("TARGETING_CLAUSE_PAUSED", "Target Paused"),
                            ("TARGETING_CLAUSE_STATUS_LIVE", "Target Enabled"),
                            ("TARGETING_CLAUSE_POLICING_SUSPENDED", "Targed Suspended"),
                            ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                            ("AD_GROUP_PAUSED", "Ad Group Paused"),
                            ("AD_GROUP_ARCHIVED", "Ad Group Archived"),
                            ("CAMPAIGN_PAUSED", "Campaign Paused"),
                            ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                            ("ACCOUNT_OUT_OF_BUDGET", "Account Budget Limited"),
                            ("PENDING_START_DATE", "Pending Start Data"),
                        ],
                        default="CAMPAIGN_STATUS_ENABLED",
                        max_length=99,
                        null=True,
                    ),
                ),
                (
                    "last_updated_date_on_amazon",
                    models.PositiveBigIntegerField(default=0, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(null=True)),
                ("report_type", models.CharField(default="", max_length=99)),
                ("impressions", models.PositiveIntegerField(default=0, null=True)),
                ("clicks", models.PositiveIntegerField(default=0, null=True)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("orders", models.PositiveIntegerField(default=0, null=True)),
                ("kenp_royalties", models.PositiveIntegerField(default=0, null=True)),
                ("tos_impressions", models.PositiveIntegerField(default=0, null=True)),
                ("tos_clicks", models.PositiveIntegerField(default=0, null=True)),
                (
                    "tos_spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "tos_sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("tos_orders", models.PositiveIntegerField(default=0, null=True)),
                (
                    "tos_kenp_royalties",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                ("pp_impressions", models.PositiveIntegerField(default=0, null=True)),
                ("pp_clicks", models.PositiveIntegerField(default=0, null=True)),
                (
                    "pp_spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "pp_sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("pp_orders", models.PositiveIntegerField(default=0, null=True)),
                (
                    "pp_kenp_royalties",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                ("ad_id", models.PositiveBigIntegerField(null=True)),
                ("ad_group_id", models.PositiveBigIntegerField(null=True)),
                ("ad_group_name", models.CharField(default="", max_length=99)),
                ("keyword_id", models.PositiveBigIntegerField(null=True)),
                ("keyword_text", models.CharField(default="", max_length=99)),
                ("query", models.CharField(default="", max_length=99)),
                ("match_type", models.CharField(default="", max_length=99)),
                ("asin", models.CharField(default="", max_length=99)),
                ("target_id", models.PositiveBigIntegerField(null=True)),
                ("target_expression", models.CharField(default="", max_length=99)),
                ("target_text", models.CharField(default="", max_length=99)),
                ("target_type", models.CharField(default="", max_length=99)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.campaign",
                        verbose_name="CampaignKey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keyword_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                (
                    "keyword_type",
                    models.CharField(
                        choices=[("Positive", "Positive"), ("Negative", "Negative")],
                        default="Positive",
                        max_length=99,
                    ),
                ),
                ("ad_group_id", models.PositiveBigIntegerField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=99,
                    ),
                ),
                ("keyword_text", models.CharField(default="", max_length=99)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("phrase", "Phrase"),
                            ("broad", "Broad"),
                            ("negativeExact", "Negative Exact"),
                            ("negativePhrase ", "Negative Phrase"),
                        ],
                        default="broad",
                        max_length=99,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        decimal_places=2, default=0.11, max_digits=8, null=True
                    ),
                ),
                (
                    "serving_status",
                    models.CharField(
                        choices=[
                            ("TARGETING_CLAUSE_ARCHIVED", "Target Archived"),
                            ("TARGETING_CLAUSE_PAUSED", "Target Paused"),
                            ("TARGETING_CLAUSE_STATUS_LIVE", "Target Enabled"),
                            ("TARGETING_CLAUSE_POLICING_SUSPENDED", "Targed Suspended"),
                            ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                            ("AD_GROUP_PAUSED", "Ad Group Paused"),
                            ("AD_GROUP_ARCHIVED", "Ad Group Archived"),
                            ("CAMPAIGN_PAUSED", "Campaign Paused"),
                            ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                            ("ACCOUNT_OUT_OF_BUDGET", "Account Budget Limited"),
                            ("PENDING_START_DATE", "Pending Start Data"),
                        ],
                        default="CAMPAIGN_STATUS_ENABLED",
                        max_length=99,
                        null=True,
                    ),
                ),
                (
                    "last_updated_date_on_amazon",
                    models.PositiveBigIntegerField(default=0, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ads_api.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pages", models.PositiveIntegerField(default=150, null=True)),
                ("kbs", models.PositiveIntegerField(default=0, null=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("Paperback", "Paperback"),
                            ("Kindle Edition", "Kindle"),
                            ("Hardcover", "Hardcover"),
                        ],
                        default="Paperback",
                        max_length=99,
                    ),
                ),
                ("asin", models.CharField(default="", max_length=99)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=8, null=True
                    ),
                ),
                (
                    "be_acos",
                    models.DecimalField(
                        decimal_places=2, default=0.4, max_digits=8, null=True
                    ),
                ),
                ("reviews", models.PositiveIntegerField(default=0, null=True)),
                ("title", models.TextField(default="", null=True)),
                ("author", models.TextField(default="", null=True)),
                ("target_bsr", models.PositiveIntegerField(default=0, null=True)),
                ("managed", models.BooleanField(default=True)),
                (
                    "campaign_discovery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="Discovery Campaign",
                    ),
                ),
                (
                    "campaign_gp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="GP Campaign",
                    ),
                ),
                (
                    "campaign_research_cat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="Category Research Campaign",
                    ),
                ),
                (
                    "campaign_research_kw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="Keyword Research Campaign",
                    ),
                ),
                (
                    "campaign_scale_asin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="ASIN Scale Campaign",
                    ),
                ),
                (
                    "campaign_scale_kw",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ads_api.campaign",
                        verbose_name="Keyword Scale Campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group_id",
                    models.PositiveBigIntegerField(db_index=True, unique=True),
                ),
                ("ad_group_name", models.CharField(default="", max_length=99)),
                (
                    "serving_status",
                    models.CharField(
                        choices=[
                            ("AD_GROUP_ARCHIVED", "Ad Group Archived"),
                            ("AD_GROUP_PAUSED", "Ad Group Paused"),
                            ("AD_GROUP_STATUS_ENABLED", "Ad Group Enabled"),
                            ("AD_POLICING_SUSPENDED", "Suspended"),
                            ("AD_GROUP_INCOMPLETE", "Ad Group Incomplete"),
                            ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                            ("CAMPAIGN_PAUSED", "Campaign Paused"),
                            ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                            ("CAMPAIGN_INCOMPLETE", "Campaign Incomplete"),
                            ("ACCOUNT_OUT_OF_BUDGET", "Account Budget Limited"),
                            ("PENDING_START_DATE", "Pending Start Data"),
                        ],
                        default="AD_GROUP_STATUS_ENABLED",
                        max_length=99,
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.campaign",
                        verbose_name="Campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
