# Generated by Django 3.2.9 on 2022-01-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="campaign_id",
            new_name="campaign_id_amazon",
        ),
    ]
