# Generated by Django 3.2.9 on 2022-01-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0005_auto_20220130_0724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adgroup",
            name="ad_group_name",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_name",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="reportdata",
            name="ad_group_name",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="reportdata",
            name="keyword_text",
            field=models.CharField(default="", max_length=254),
        ),
    ]
