# Generated by Django 3.2.9 on 2022-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0006_auto_20220130_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdata",
            name="placement",
            field=models.CharField(default="", max_length=254),
        ),
    ]
