# Generated by Django 3.2.9 on 2022-02-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0007_reportdata_placement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdata",
            name="query",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="reportdata",
            name="target_expression",
            field=models.CharField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="reportdata",
            name="target_text",
            field=models.CharField(default="", max_length=254),
        ),
    ]
