# Generated by Django 3.2.9 on 2022-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0008_auto_20220203_0834"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_clicks",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_impressions",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_kenp_royalties",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_orders",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_sales",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="pp_spend",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_clicks",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_impressions",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_kenp_royalties",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_orders",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_sales",
        ),
        migrations.RemoveField(
            model_name="reportdata",
            name="tos_spend",
        ),
    ]
