# Generated by Django 3.2.9 on 2022-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0009_auto_20220203_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_purpose",
            field=models.CharField(
                choices=[
                    ("Auto-Discovery", "Auto-Discovery"),
                    ("Cat-Research", "Cat-Research"),
                    ("Broad-Research", "Broad-Research"),
                    ("Exact-Scale", "Exact-Scale"),
                    ("Product-Scale", "Product-Scale"),
                    ("GP", "GP"),
                ],
                default="",
                max_length=99,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
