# Generated by Django 3.2.9 on 2022-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0010_auto_20220211_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="adgroup",
            name="manual_type",
            field=models.CharField(
                choices=[("Product", "Product"), ("Keyword", "Keyword")],
                default="",
                max_length=99,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="serving_status",
            field=models.CharField(
                choices=[
                    ("TARGETING_CLAUSE_ARCHIVED", "Target Archived"),
                    ("TARGETING_CLAUSE_PAUSED", "Target Paused"),
                    ("TARGETING_CLAUSE_STATUS_LIVE", "Target Enabled"),
                    ("TARGETING_CLAUSE_POLICING_SUSPENDED", "Targed Suspended"),
                    ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                    ("AD_GROUP_PAUSED", "Ad Group Paused"),
                    ("AD_GROUP_ARCHIVED", "Ad Group Archived"),
                    ("CAMPAIGN_PAUSED", "Campaign Paused"),
                    ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                    ("ACCOUNT_OUT_OF_BUDGET", "Account Budget Limited"),
                    ("PENDING_START_DATE", "Pending Start Data"),
                ],
                default="TARGETING_CLAUSE_STATUS_LIVE",
                max_length=99,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="serving_status",
            field=models.CharField(
                choices=[
                    ("TARGETING_CLAUSE_ARCHIVED", "Target Archived"),
                    ("TARGETING_CLAUSE_PAUSED", "Target Paused"),
                    ("TARGETING_CLAUSE_STATUS_LIVE", "Target Enabled"),
                    ("TARGETING_CLAUSE_POLICING_SUSPENDED", "Targed Suspended"),
                    ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                    ("AD_GROUP_PAUSED", "Ad Group Paused"),
                    ("AD_GROUP_ARCHIVED", "Ad Group Archived"),
                    ("CAMPAIGN_PAUSED", "Campaign Paused"),
                    ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                    ("ACCOUNT_OUT_OF_BUDGET", "Account Budget Limited"),
                    ("PENDING_START_DATE", "Pending Start Data"),
                ],
                default="TARGETING_CLAUSE_STATUS_LIVE",
                max_length=99,
                null=True,
            ),
        ),
    ]
