# Generated by Django 3.2.9 on 2022-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0011_auto_20220221_1546"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accessible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_purpose",
            field=models.CharField(
                choices=[
                    ("Auto-Discovery", "Auto-Discovery"),
                    ("Cat-Research", "Cat-Research"),
                    ("Broad-Research", "Broad-Research"),
                    ("Exact-Scale", "Exact-Scale"),
                    ("Product-Comp", "Product-Comp"),
                    ("GP", "GP"),
                ],
                default="",
                max_length=99,
                null=True,
            ),
        ),
    ]
