# Generated by Django 3.2.9 on 2022-03-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0014_adgroup_default_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profit_mode",
            field=models.BooleanField(default=False),
        ),
    ]
