# Generated by Django 3.2.9 on 2022-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0015_profile_profit_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(
                choices=[
                    ("Paperback", "Paperback"),
                    ("Kindle Edition", "Kindle"),
                    ("Hardcover", "Hardcover"),
                ],
                default="Paperback",
                max_length=99,
                null=True,
            ),
        ),
    ]
