# Generated by Django 3.2.9 on 2022-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0016_alter_book_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_size",
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
