# Generated by Django 3.2.9 on 2022-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0017_report_report_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_details",
            field=models.CharField(default="", max_length=255),
        ),
    ]
