# Generated by Django 3.2.9 on 2022-03-16 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0019_auto_20220316_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="placement_pp_mult",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(900),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="placement_tos_mult",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(900),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
