# Generated by Django 3.2.9 on 2022-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0022_alter_campaign_portfolio_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="target_acos",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
