# Generated by Django 3.2.9 on 2022-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0023_alter_campaign_target_acos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="current_bsr",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
