# Generated by Django 3.2.9 on 2022-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0024_alter_book_current_bsr"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="in_catalog",
            field=models.BooleanField(default=False),
        ),
    ]
