# Generated by Django 3.2.9 on 2022-04-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0025_book_in_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
