# Generated by Django 3.2.9 on 2022-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0027_alter_book_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="brand_campaign_id",
            field=models.CharField(blank=True, default="", max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="serving_status",
            field=models.CharField(
                choices=[
                    ("CAMPAIGN_ARCHIVED", "Archived"),
                    ("CAMPAIGN_PAUSED", "Paused"),
                    ("CAMPAIGN_STATUS_ENABLED", "Enabled"),
                    ("ADVERTISER_PAYMENT_FAILED", "Payment Failed"),
                    ("ADVERTISER_PAYMENT_FAILURE", "Payment Failure"),
                    ("CAMPAIGN_OUT_OF_BUDGET", "Campaign Budget Limited"),
                    ("PENDING_START_DATE", "Pending Start Date"),
                    ("CAMPAIGN_INCOMPLETE", "Incomplete"),
                    ("ENDED", "Ended"),
                    ("RUNNING", "Running"),
                ],
                default="CAMPAIGN_STATUS_ENABLED",
                max_length=99,
                null=True,
            ),
        ),
    ]
