# Generated by Django 3.2.9 on 2022-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0028_auto_20220502_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="adgroup",
            name="brand_ad_group_id",
            field=models.CharField(blank=True, default="", max_length=99, null=True),
        ),
    ]
