# Generated by Django 3.2.9 on 2022-05-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0029_adgroup_brand_ad_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asin", models.CharField(default="", max_length=99)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(default="", max_length=250, null=True)),
                ("bsr", models.PositiveIntegerField(blank=True, default=0, null=True)),
                (
                    "country_code",
                    models.CharField(
                        choices=[
                            ("US", "Us"),
                            ("CA", "Ca"),
                            ("MX", "Mx"),
                            ("UK", "Uk"),
                            ("AU", "Au"),
                            ("DE", "De"),
                            ("ES", "Es"),
                            ("FR", "Fr"),
                        ],
                        default="US",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="DefaultKeywords",
            new_name="DefaultKeyword",
        ),
        migrations.CreateModel(
            name="Relevance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relevant", models.BooleanField(default=False)),
                ("checked", models.BooleanField(default=False)),
                ("targeting", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "new_release",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.newrelease",
                        verbose_name="New Release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
