# Generated by Django 3.2.13 on 2022-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0030_auto_20220526_1352"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultKeyword",
        ),
    ]
