# Generated by Django 3.2.13 on 2022-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0031_delete_defaultkeyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_purpose",
            field=models.CharField(
                choices=[
                    ("Auto-Discovery", "Auto-Discovery"),
                    ("Cat-Research", "Cat-Research"),
                    ("Broad-Research", "Broad-Research"),
                    ("Broad-Research-Single", "Broad-Research-Single"),
                    ("Exact-Scale", "Exact-Scale"),
                    ("Exact-Scale-Single", "Exact-Scale-Single"),
                    ("Product-Comp", "Product-Comp"),
                    ("GP", "GP"),
                ],
                default="",
                max_length=99,
                null=True,
            ),
        ),
    ]
