# Generated by Django 3.2.13 on 2022-12-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0036_auto_20221202_0824"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("report_type", "report_for_date", "profile_id")},
        ),
        migrations.AlterUniqueTogether(
            name="reportdata",
            unique_together={
                (
                    "ad_id",
                    "keyword_id",
                    "target_id",
                    "asin",
                    "query",
                    "placement",
                    "campaign",
                    "date",
                    "report_type",
                )
            },
        ),
    ]
