# Generated by Django 3.2.13 on 2023-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0037_auto_20221227_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="eligible",
            field=models.BooleanField(default=True),
        ),
    ]
