# Generated by Django 3.2.13 on 2023-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0038_book_eligible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(
                choices=[
                    ("Paperback", "Paperback"),
                    ("Kindle", "Kindle"),
                    ("Hardcover", "Hardcover"),
                    ("Mass Market Paperback", "Mass Market Paperback"),
                    ("Leather Bound", "Leather Bound"),
                    ("Spiral-bound", "Spiral-bound"),
                ],
                default="Paperback",
                max_length=99,
                null=True,
            ),
        ),
    ]
