# Generated by Django 3.2.13 on 2023-01-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0039_alter_book_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="report_details",
        ),
    ]
