# Generated by Django 3.2.13 on 2023-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0040_remove_report_report_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="campaigns",
            field=models.ManyToManyField(to="ads_api.Campaign"),
        ),
    ]
