# Generated by Django 3.2.13 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0041_book_campaigns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="campaigns",
            field=models.ManyToManyField(related_name="books", to="ads_api.Campaign"),
        ),
    ]
