# Generated by Django 3.2.13 on 2023-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0042_alter_book_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="conservative",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="launch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
