# Generated by Django 3.2.13 on 2023-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0043_auto_20230130_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="research_percentage",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="surplus_budget",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
