# Generated by Django 3.2.13 on 2023-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0044_auto_20230130_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="monthly_budget",
            field=models.PositiveIntegerField(blank=True, default=999999, null=True),
        ),
    ]
