# Generated by Django 3.2.13 on 2023-02-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0045_alter_profile_monthly_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="research_mode",
        ),
    ]
