# Generated by Django 3.2.13 on 2023-02-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0046_remove_profile_research_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adgroup",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_groups",
                to="ads_api.campaign",
                verbose_name="Campaign",
            ),
        ),
    ]
