# Generated by Django 3.2.13 on 2023-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0047_alter_adgroup_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdata",
            name="units_sold_14d",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
