# Generated by Django 3.2.13 on 2023-02-14 08:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0049_auto_20230213_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="daily_budget",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("20.01"), max_digits=12
            ),
        ),
    ]
