# Generated by Django 3.2.13 on 2023-02-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0050_alter_campaign_daily_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateBookPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=9.99, max_digits=8, null=True
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.book",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "book", "price")},
            },
        ),
    ]
