# Generated by Django 3.2.13 on 2023-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0053_alter_report_report_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_location",
            field=models.CharField(default="", max_length=4056),
        ),
    ]
