# Generated by Django 3.2.13 on 2023-03-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0053_alter_campaign_campaign_purpose"),
        ("ads_api", "0054_alter_report_report_location"),
    ]

    operations = []
