# Generated by Django 3.2.13 on 2023-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0055_merge_20230302_0620"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "In progress"),
                    ("COMPLETED", "Success"),
                    ("FAILURE", "Amazon Failure"),
                    ("INITIAL_PROCCESED", "Internal Processed"),
                    ("INTERNAL_FAILURE", "Internal Failure"),
                ],
                default="IN_PROGRESS",
                max_length=99,
            ),
        ),
    ]
