# Generated by Django 3.2.13 on 2023-03-21 10:48

import apps.ads_api.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0056_auto_20230307_0721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Success"),
                    ("FAILED", "Amazon Failure"),
                    ("INTERNAL_PROCESSED", "Internal Processed"),
                    ("INTERNAL_FAILURE", "Internal Failure"),
                    ("EMPTY", "Empty"),
                ],
                default=apps.ads_api.constants.ReportStatus["PENDING"],
                max_length=99,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datebookprice",
            unique_together={("date", "book")},
        ),
    ]
