# Generated by Django 3.2.13 on 2023-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0058_auto_20230322_0903"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(null=True)),
                ("report_type", models.CharField(default="", max_length=99)),
                ("impressions", models.PositiveIntegerField(default=0, null=True)),
                ("clicks", models.PositiveIntegerField(default=0, null=True)),
                (
                    "spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("orders", models.PositiveIntegerField(default=0, null=True)),
                ("kenp_royalties", models.PositiveIntegerField(default=0, null=True)),
                ("placement", models.CharField(default="", max_length=254)),
                ("ad_id", models.PositiveBigIntegerField(null=True)),
                ("ad_group_id", models.PositiveBigIntegerField(null=True)),
                ("ad_group_name", models.CharField(default="", max_length=254)),
                ("keyword_id", models.PositiveBigIntegerField(null=True)),
                ("keyword_text", models.CharField(default="", max_length=254)),
                ("query", models.CharField(default="", max_length=254)),
                ("match_type", models.CharField(default="", max_length=99)),
                ("asin", models.CharField(default="", max_length=99)),
                ("target_id", models.PositiveBigIntegerField(null=True)),
                ("target_expression", models.CharField(default="", max_length=254)),
                ("target_text", models.CharField(default="", max_length=254)),
                ("target_type", models.CharField(default="", max_length=99)),
                ("units_sold_14d", models.PositiveIntegerField(default=0, null=True)),
                (
                    "attributed_conversions_30d",
                    models.PositiveIntegerField(default=0, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads_api.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "ad_id",
                        "keyword_id",
                        "target_id",
                        "asin",
                        "query",
                        "placement",
                        "campaign",
                        "date",
                        "report_type",
                    )
                },
            },
        ),
    ]
