# Generated by Django 3.2.13 on 2023-04-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0059_recentreportdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="ads_api.profile",
                verbose_name="Profile",
            ),
        ),
        migrations.AlterField(
            model_name="productad",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_ads",
                to="ads_api.campaign",
                verbose_name="Campaign",
            ),
        ),
    ]
