# Generated by Django 3.2.13 on 2023-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads_api", "0060_auto_20230419_0932"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("report_type", "profile_id")},
        ),
    ]
