# Generated by Django 3.2.13 on 2023-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0062_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='serving_status',
            field=models.CharField(choices=[('ADVERTISER_OUT_OF_BUDGET', 'ADVERTISER_OUT_OF_BUDGET'), ('ADVERTISER_PAYMENT_FAILURE', 'ADVERTISER_PAYMENT_FAILURE'), ('ADVERTISER_POLICING_PENDING_REVIEW', 'ADVERTISER_POLICING_PENDING_REVIEW'), ('CAMPAIGN_OUT_OF_BUDGET', 'CAMPAIGN_OUT_OF_BUDGET'), ('CAMPAIGN_STATUS_ENABLED', 'CAMPAIGN_STATUS_ENABLED'), ('PENDING_REVIEW', 'PENDING_REVIEW'), ('PENDING_START_DATE', 'PENDING_START_DATE'), ('PORTFOLIO_OUT_OF_BUDGET', 'PORTFOLIO_OUT_OF_BUDGET'), ('PORTFOLIO_PENDING_START_DATE', 'PORTFOLIO_PENDING_START_DATE'), ('PORTFOLIO_STATUS_ENABLED', 'PORTFOLIO_STATUS_ENABLED'), ('ADVERTISER_ARCHIVED', 'ADVERTISER_ARCHIVED'), ('ADVERTISER_PAUSED', 'ADVERTISER_PAUSED'), ('ADVERTISER_POLICING_SUSPENDED', 'ADVERTISER_POLICING_SUSPENDED'), ('CAMPAIGN_ARCHIVED', 'CAMPAIGN_ARCHIVED'), ('CAMPAIGN_INCOMPLETE', 'CAMPAIGN_INCOMPLETE'), ('CAMPAIGN_PAUSED', 'CAMPAIGN_PAUSED'), ('ENDED', 'ENDED'), ('OTHER', 'OTHER'), ('PORTFOLIO_ARCHIVED', 'PORTFOLIO_ARCHIVED'), ('PORTFOLIO_ENDED', 'PORTFOLIO_ENDED'), ('PORTFOLIO_PAUSED', 'PORTFOLIO_PAUSED'), ('REJECTED', 'REJECTED'), ('AD_GROUP_LOW_BID', 'AD_GROUP_LOW_BID'), ('AD_GROUP_POLICING_PENDING_REVIEW', 'AD_GROUP_POLICING_PENDING_REVIEW'), ('AD_GROUP_STATUS_ENABLED', 'AD_GROUP_STATUS_ENABLED'), ('AD_GROUP_INCOMPLETE', 'AD_GROUP_INCOMPLETE'), ('AD_GROUP_ARCHIVED', 'AD_GROUP_ARCHIVED'), ('AD_GROUP_PAUSED', 'AD_GROUP_PAUSED'), ('AD_GROUP_POLICING_CREATIVE_REJECTED', 'AD_GROUP_POLICING_CREATIVE_REJECTED')], default='AD_GROUP_STATUS_ENABLED', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('ENABLING', 'Enabling'), ('OTHER', 'Other')], default='ENABLED', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='bidding_strategy',
            field=models.CharField(choices=[('LEGACY_FOR_SALES', 'Down Only'), ('AUTO_FOR_SALES', 'Up & Down'), ('MANUAL', 'Fixed Bids')], default='LEGACY_FOR_SALES', max_length=99),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='serving_status',
            field=models.CharField(choices=[('ADVERTISER_OUT_OF_BUDGET', 'ADVERTISER_OUT_OF_BUDGET'), ('ADVERTISER_PAYMENT_FAILURE', 'ADVERTISER_PAYMENT_FAILURE'), ('ADVERTISER_POLICING_PENDING_REVIEW', 'ADVERTISER_POLICING_PENDING_REVIEW'), ('CAMPAIGN_OUT_OF_BUDGET', 'CAMPAIGN_OUT_OF_BUDGET'), ('CAMPAIGN_STATUS_ENABLED', 'CAMPAIGN_STATUS_ENABLED'), ('PENDING_REVIEW', 'PENDING_REVIEW'), ('PENDING_START_DATE', 'PENDING_START_DATE'), ('PORTFOLIO_OUT_OF_BUDGET', 'PORTFOLIO_OUT_OF_BUDGET'), ('PORTFOLIO_PENDING_START_DATE', 'PORTFOLIO_PENDING_START_DATE'), ('PORTFOLIO_STATUS_ENABLED', 'PORTFOLIO_STATUS_ENABLED'), ('ADVERTISER_ARCHIVED', 'ADVERTISER_ARCHIVED'), ('ADVERTISER_PAUSED', 'ADVERTISER_PAUSED'), ('ADVERTISER_POLICING_SUSPENDED', 'ADVERTISER_POLICING_SUSPENDED'), ('CAMPAIGN_ARCHIVED', 'CAMPAIGN_ARCHIVED'), ('CAMPAIGN_INCOMPLETE', 'CAMPAIGN_INCOMPLETE'), ('CAMPAIGN_PAUSED', 'CAMPAIGN_PAUSED'), ('ENDED', 'ENDED'), ('OTHER', 'OTHER'), ('PORTFOLIO_ARCHIVED', 'PORTFOLIO_ARCHIVED'), ('PORTFOLIO_ENDED', 'PORTFOLIO_ENDED'), ('PORTFOLIO_PAUSED', 'PORTFOLIO_PAUSED'), ('REJECTED', 'REJECTED'), ('ACCOUNT_OUT_OF_BUDGET', 'ACCOUNT_OUT_OF_BUDGET')], default='CAMPAIGN_STATUS_ENABLED', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('ENABLING', 'Enabling'), ('OTHER', 'Other')], default='ENABLED', max_length=99),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='targeting_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('OTHER', 'Other')], default='MANUAL', max_length=99),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='match_type',
            field=models.CharField(choices=[('EXACT', 'Exact'), ('PHRASE', 'Phrase'), ('BROAD', 'Broad'), ('NEGATIVE_EXACT', 'Negative Exact'), ('NEGATIVE_PHRASE', 'Negative Phrase'), ('NEGATIVE_BROAD', 'Negative Broad'), ('OTHER', 'Other')], default='BROAD', max_length=99),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('ENABLING', 'Enabling'), ('OTHER', 'Other')], default='ENABLED', max_length=99),
        ),
        migrations.AlterField(
            model_name='productad',
            name='serving_status',
            field=models.CharField(choices=[('ADVERTISER_OUT_OF_BUDGET', 'ADVERTISER_OUT_OF_BUDGET'), ('ADVERTISER_PAYMENT_FAILURE', 'ADVERTISER_PAYMENT_FAILURE'), ('ADVERTISER_POLICING_PENDING_REVIEW', 'ADVERTISER_POLICING_PENDING_REVIEW'), ('CAMPAIGN_OUT_OF_BUDGET', 'CAMPAIGN_OUT_OF_BUDGET'), ('CAMPAIGN_STATUS_ENABLED', 'CAMPAIGN_STATUS_ENABLED'), ('PENDING_REVIEW', 'PENDING_REVIEW'), ('PENDING_START_DATE', 'PENDING_START_DATE'), ('PORTFOLIO_OUT_OF_BUDGET', 'PORTFOLIO_OUT_OF_BUDGET'), ('PORTFOLIO_PENDING_START_DATE', 'PORTFOLIO_PENDING_START_DATE'), ('PORTFOLIO_STATUS_ENABLED', 'PORTFOLIO_STATUS_ENABLED'), ('ADVERTISER_ARCHIVED', 'ADVERTISER_ARCHIVED'), ('ADVERTISER_PAUSED', 'ADVERTISER_PAUSED'), ('ADVERTISER_POLICING_SUSPENDED', 'ADVERTISER_POLICING_SUSPENDED'), ('CAMPAIGN_ARCHIVED', 'CAMPAIGN_ARCHIVED'), ('CAMPAIGN_INCOMPLETE', 'CAMPAIGN_INCOMPLETE'), ('CAMPAIGN_PAUSED', 'CAMPAIGN_PAUSED'), ('ENDED', 'ENDED'), ('OTHER', 'OTHER'), ('PORTFOLIO_ARCHIVED', 'PORTFOLIO_ARCHIVED'), ('PORTFOLIO_ENDED', 'PORTFOLIO_ENDED'), ('PORTFOLIO_PAUSED', 'PORTFOLIO_PAUSED'), ('REJECTED', 'REJECTED'), ('AD_STATUS_LIVE', 'AD_STATUS_LIVE'), ('AD_CREATION_OFFLINE_IN_PROGRESS', 'AD_CREATION_OFFLINE_IN_PROGRESS'), ('AD_CREATION_OFFLINE_PENDING', 'AD_CREATION_OFFLINE_PENDING'), ('AD_ELIGIBLE', 'AD_ELIGIBLE'), ('AD_POLICING_PENDING_REVIEW', 'AD_POLICING_PENDING_REVIEW'), ('ADVERTISER_ACCOUNT_OUT_OF_BUDGET', 'ADVERTISER_ACCOUNT_OUT_OF_BUDGET'), ('ADVERTISER_EXCEED_SPENDS_LIMIT', 'ADVERTISER_EXCEED_SPENDS_LIMIT'), ('ADVERTISER_STATUS_ENABLED', 'ADVERTISER_STATUS_ENABLED'), ('CAMPAIGN_PENDING_START_DATE', 'CAMPAIGN_PENDING_START_DATE'), ('ELIGIBLE', 'ELIGIBLE'), ('SECURITY_SCAN_PENDING_REVIEW', 'SECURITY_SCAN_PENDING_REVIEW'), ('ACCOUNT_OUT_OF_BUDGET', 'ACCOUNT_OUT_OF_BUDGET'), ('AD_ARCHIVED', 'AD_ARCHIVED'), ('AD_CREATION_FAILED', 'AD_CREATION_FAILED'), ('AD_CREATION_OFFLINE_FAILED', 'AD_CREATION_OFFLINE_FAILED'), ('AD_INELIGIBLE', 'AD_INELIGIBLE'), ('AD_LANDING_PAGE_NOT_AVAILABLE', 'AD_LANDING_PAGE_NOT_AVAILABLE'), ('AD_MISSING_DECORATION', 'AD_MISSING_DECORATION'), ('AD_MISSING_IMAGE', 'AD_MISSING_IMAGE'), ('AD_NO_PURCHASABLE_OFFER', 'AD_NO_PURCHASABLE_OFFER'), ('AD_NOT_BUYABLE', 'AD_NOT_BUYABLE'), ('AD_NOT_IN_BUYBOX', 'AD_NOT_IN_BUYBOX'), ('AD_OUT_OF_STOCK', 'AD_OUT_OF_STOCK'), ('AD_PAUSED', 'AD_PAUSED'), ('AD_POLICING_SUSPENDED', 'AD_POLICING_SUSPENDED'), ('CAMPAIGN_ADS_NOT_DELIVERING', 'CAMPAIGN_ADS_NOT_DELIVERING'), ('CAMPAIGN_ENDED', 'CAMPAIGN_ENDED'), ('INELIGIBLE', 'INELIGIBLE'), ('LANDING_PAGE_NOT_AVAILABLE', 'LANDING_PAGE_NOT_AVAILABLE'), ('MISSING_DECORATION', 'MISSING_DECORATION'), ('MISSING_IMAGE', 'MISSING_IMAGE'), ('NO_INVENTORY', 'NO_INVENTORY'), ('NO_PURCHASABLE_OFFER', 'NO_PURCHASABLE_OFFER'), ('NOT_BUYABLE', 'NOT_BUYABLE'), ('NOT_IN_BUYBOX', 'NOT_IN_BUYBOX'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('PIR_RULE_EXCLUDED', 'PIR_RULE_EXCLUDED'), ('SECURITY_SCAN_REJECTED', 'SECURITY_SCAN_REJECTED'), ('STATUS_UNAVAILABLE', 'STATUS_UNAVAILABLE')], default='', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='productad',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('ENABLING', 'Enabling'), ('OTHER', 'Other')], default='ENABLED', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='state',
            field=models.CharField(choices=[('ENABLED', 'Enabled'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived'), ('ENABLING', 'Enabling'), ('OTHER', 'Other')], default='ENABLED', max_length=99),
        ),
        migrations.AlterField(
            model_name='target',
            name='targeting_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto'), ('OTHER', 'Other')], default='MANUAL', max_length=99),
        ),
        migrations.AlterUniqueTogether(
            name='adgroup',
            unique_together={('ad_group_id', 'campaign')},
        ),
    ]
