# Generated by Django 3.2.13 on 2023-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0063_auto_20230530_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='ad_group_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
