# Generated by Django 3.2.13 on 2023-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0064_alter_adgroup_ad_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_purpose',
            field=models.CharField(choices=[('Auto-Discovery', 'Auto-Discovery'), ('Cat-Research', 'Cat-Research'), ('Broad-Research', 'Broad-Research'), ('Broad-Research-Single', 'Broad-Research-Single'), ('Exact-Scale', 'Exact-Scale'), ('Exact-Scale-Single', 'Exact-Scale-Single'), ('Product-Comp', 'Product-Comp'), ('Product-Own', 'Product-Own'), ('Product-Self', 'Product-Self'), ('Product-Exp', 'Product-Exp'), ('GP', 'GP'), ('Auto-GP', 'Auto-GP')], default='', max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='productad',
            name='product_ad_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='productad',
            unique_together={('product_ad_id', 'campaign', 'ad_group')},
        ),
    ]
