# Generated by Django 3.2.13 on 2023-06-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0065_auto_20230607_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='ads_api.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_api.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='ad_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_api.adgroup', verbose_name='Ad Group'),
        ),
        migrations.AlterField(
            model_name='productad',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ads', to='ads_api.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='target',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_api.campaign', verbose_name='Campaign'),
        ),
    ]
