# Generated by Django 3.2.13 on 2023-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads_api", "0066_auto_20230608_0821"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="external_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="external_created",
            field=models.BooleanField(default=False),
        ),
    ]
