# Generated by Django 3.2.13 on 2023-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads_api", "0067_auto_20230612_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="keyword_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="target_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
