# Generated by Django 3.2.13 on 2023-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0069_auto_20230613_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='creation_retries_count',
            field=models.IntegerField(default=0),
        ),
    ]
