# Generated by Django 3.2.13 on 2023-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0070_campaign_creation_retries_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='datebookprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productad',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recentreportdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reportdata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='adgroup',
            constraint=models.UniqueConstraint(fields=('ad_group_id', 'campaign'), name='unique_ad_group'),
        ),
        migrations.AddConstraint(
            model_name='datebookprice',
            constraint=models.UniqueConstraint(fields=('date', 'book'), name='unique_date_book_price'),
        ),
        migrations.AddConstraint(
            model_name='productad',
            constraint=models.UniqueConstraint(fields=('product_ad_id', 'campaign', 'ad_group'), name='unique_product_ad'),
        ),
        migrations.AddConstraint(
            model_name='recentreportdata',
            constraint=models.UniqueConstraint(fields=('ad_id', 'keyword_id', 'target_id', 'asin', 'query', 'placement', 'campaign', 'date', 'report_type'), name='unique_recent_report_data'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_type', 'profile_id', 'start_date', 'end_date'), name='unique_report'),
        ),
        migrations.AddConstraint(
            model_name='reportdata',
            constraint=models.UniqueConstraint(fields=('ad_id', 'keyword_id', 'target_id', 'asin', 'query', 'placement', 'campaign', 'date', 'report_type'), name='unique_report_data'),
        ),
    ]
