# Generated by Django 3.2.13 on 2023-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0071_auto_20230620_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='be_acos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
