# Generated by Django 3.2.13 on 2023-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_api', '0072_auto_20230714_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentreportdata',
            name='top_of_search_impression_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='top_of_search_impression_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_purpose',
            field=models.CharField(choices=[('Auto-Discovery', 'Auto-Discovery'), ('Auto-Discovery-Loose-Match', 'Auto-Discovery-Loose-Match'), ('Auto-Discovery-Close-Match', 'Auto-Discovery-Close-Match'), ('Auto-Discovery-Substitutes', 'Auto-Discovery-Substitutes'), ('Auto-Discovery-Complements', 'Auto-Discovery-Complements'), ('Cat-Research', 'Cat-Research'), ('Broad-Research', 'Broad-Research'), ('Broad-Research-Single', 'Broad-Research-Single'), ('Exact-Scale', 'Exact-Scale'), ('Exact-Scale-Single', 'Exact-Scale-Single'), ('Product-Comp', 'Product-Comp'), ('Product-Own', 'Product-Own'), ('Product-Self', 'Product-Self'), ('Product-Exp', 'Product-Exp'), ('GP', 'GP'), ('Auto-GP', 'Auto-GP')], default='', max_length=99, null=True),
        ),
    ]
