# Generated by Django 3.2.13 on 2023-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(db_index=True, max_length=10, unique=True)),
                ('title', models.CharField(max_length=2048)),
                ('bsr', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
