# Generated by Django 3.2.13 on 2023-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcache',
            name='bsr',
            field=models.IntegerField(),
        ),
    ]
